# Generated by Django 5.2.1 on 2025-05-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="warehouse",
            name="is_active",
        ),
    ]
